name: Test Libft avec Francinette

on: [push]

jobs:
  test_libft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          # Francinette peut nécessiter 'make', 'gcc', etc., déjà présents sur ubuntu-latest,
          # mais on s'assure d'avoir 'git' et 'wget' ou 'curl'
          sudo apt-get update
          sudo apt-get install -y git

      - name: Clone Francinette
        run: |
          git clone https://github.com/xicodomingues/francinette.git "$HOME/francinette"


      - name: Run Francinette Tests
        run: |
          $HOME/francinette/tester.sh $GITHUB_WORKSPACE

